Repository openshift/gcp-filestore-csi-driver-operator, pull requests merged in 2024-02, with the labels that each got.

#82 OCPBUGS-29072: Add infrastructure annotations
  config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, lgtm, approved, jira/valid-reference

#81 OCPBUGS-26924: Add healtcheck for node-registrar
  assets/node.yaml
Labels: jira/valid-bug, lgtm, approved, jira/valid-reference

#83 OCPBUGS-29677: Add infrastructure annotations
  config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, lgtm, approved, backport-risk-assessed, qe-approved, staff-eng-approved, cherry-pick-approved, jira/valid-reference

#84 OCPBUGS-29678: Add infrastructure annotations
  config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, lgtm, approved, backport-risk-assessed, qe-approved, cherry-pick-approved, jira/valid-reference
